SELECT *
FROM supply_chain
LIMIT 5;

-- =====================================================
-- SUPPLY CHAIN ANALYTICS PROJECT
-- SQL BUSINESS QUERIES
-- Author: Mrunal Shinde
-- =====================================================

-- -----------------------------------------------------
-- Query 1: Total Sales
-- Business Question:
-- What is the total sales revenue generated by the company?
-- -----------------------------------------------------

SELECT
    SUM("Sales") AS total_sales
FROM supply_chain;

-- -----------------------------------------------------
-- Query 2: Total Profit
-- Business Question:
-- What is the total profit earned by the company?
-- -----------------------------------------------------

SELECT
    SUM("Profit") AS total_profit
FROM supply_chain;

-- -----------------------------------------------------
-- Query 3: Total Orders
-- Business Question:
-- How many unique orders were placed by customers?
-- -----------------------------------------------------

SELECT
    COUNT(DISTINCT "Order Id") AS total_orders
FROM supply_chain;

-- -----------------------------------------------------
-- Query 4: Total Customers
-- Business Question:
-- How many unique customers made purchases?
-- -----------------------------------------------------

SELECT
    COUNT(DISTINCT "Customer Id") AS total_customers
FROM supply_chain;

-- -----------------------------------------------------
-- Query 5: Average Order Value
-- Business Question:
-- What is the average sales value per order record?
-- -----------------------------------------------------

SELECT
    AVG("Sales") AS average_order_value
FROM supply_chain;

-- -----------------------------------------------------
-- Query 6: Top 10 Product Categories by Sales
-- Business Question:
-- Which product categories generate the highest sales revenue?
-- -----------------------------------------------------

SELECT
    "Category Name",
    SUM("Sales") AS total_sales
FROM supply_chain
GROUP BY "Category Name"
ORDER BY total_sales DESC
LIMIT 10;

-- -----------------------------------------------------
-- Query 7: Top 10 Products by Sales
-- Business Question:
-- Which products generate the highest sales revenue?
-- -----------------------------------------------------

SELECT
    "Product Name",
    SUM("Sales") AS total_sales
FROM supply_chain
GROUP BY "Product Name"
ORDER BY total_sales DESC
LIMIT 10;

-- -----------------------------------------------------
-- Query 8: Sales by Market
-- Business Question:
-- Which markets contribute the highest sales?
-- -----------------------------------------------------

SELECT
    "Market",
    SUM("Sales") AS total_sales
FROM supply_chain
GROUP BY "Market"
ORDER BY total_sales DESC;

-- -----------------------------------------------------
-- Query 9: Sales by Customer Segment
-- Business Question:
-- Which customer segment generates the highest sales?
-- -----------------------------------------------------

SELECT
    "Customer Segment",
    SUM("Sales") AS total_sales
FROM supply_chain
GROUP BY "Customer Segment"
ORDER BY total_sales DESC;

-- -----------------------------------------------------
-- Query 10: Orders by Shipping Mode
-- Business Question:
-- Which shipping mode is used most frequently?
-- -----------------------------------------------------

SELECT
    "Shipping Mode",
    COUNT(*) AS total_orders
FROM supply_chain
GROUP BY "Shipping Mode"
ORDER BY total_orders DESC;

-- -----------------------------------------------------
-- Query 11: Top 10 Countries by Sales
-- Business Question:
-- Which countries generate the highest sales revenue?
-- -----------------------------------------------------

SELECT
    "Order Country",
    SUM("Sales") AS total_sales
FROM supply_chain
GROUP BY "Order Country"
ORDER BY total_sales DESC
LIMIT 10;

-- -----------------------------------------------------
-- Query 12: Top 10 Regions by Sales
-- Business Question:
-- Which regions contribute the highest sales?
-- -----------------------------------------------------

SELECT
    "Order Region",
    SUM("Sales") AS total_sales
FROM supply_chain
GROUP BY "Order Region"
ORDER BY total_sales DESC
LIMIT 10;

-- -----------------------------------------------------
-- Query 13: Top 10 Products by Profit
-- Business Question:
-- Which products generate the highest profit?
-- -----------------------------------------------------

SELECT
    "Product Name",
    SUM("Profit") AS total_profit
FROM supply_chain
GROUP BY "Product Name"
ORDER BY total_profit DESC
LIMIT 10;

-- -----------------------------------------------------
-- Query 14: Profit by Category
-- Business Question:
-- Which product categories generate the highest profit?
-- -----------------------------------------------------

SELECT
    "Category Name",
    SUM("Profit") AS total_profit
FROM supply_chain
GROUP BY "Category Name"
ORDER BY total_profit DESC;

-- -----------------------------------------------------
-- Query 15: Top 10 Customers
-- Business Question:
-- Which customers contribute the highest sales?
-- -----------------------------------------------------

SELECT
    "Customer Id",
    SUM("Sales") AS total_sales
FROM supply_chain
GROUP BY "Customer Id"
ORDER BY total_sales DESC
LIMIT 10;

-- -----------------------------------------------------
-- Query 16: Average Shipping Time
-- Business Question:
-- What is the average actual shipping time?
-- -----------------------------------------------------

SELECT
    AVG("Days for shipping (real)") AS avg_shipping_days
FROM supply_chain;

-- -----------------------------------------------------
-- Query 17: Delivery Status Distribution
-- Business Question:
-- How many orders fall under each delivery status?
-- -----------------------------------------------------

SELECT
    "Delivery Status",
    COUNT(*) AS total_orders
FROM supply_chain
GROUP BY "Delivery Status"
ORDER BY total_orders DESC;

-- -----------------------------------------------------
-- Query 18: Late Delivery Risk
-- Business Question:
-- How many orders are at risk of late delivery?
-- -----------------------------------------------------

SELECT
    "Late_delivery_risk",
    COUNT(*) AS total_orders
FROM supply_chain
GROUP BY "Late_delivery_risk";

-- -----------------------------------------------------
-- Query 19: Average Profit by Market
-- Business Question:
-- Which markets have the highest average profit per order?
-- -----------------------------------------------------

SELECT
    "Market",
    AVG("Profit") AS average_profit
FROM supply_chain
GROUP BY "Market"
ORDER BY average_profit DESC;

-- -----------------------------------------------------
-- Query 20: Most Expensive Products
-- Business Question:
-- Which products have the highest product price?
-- -----------------------------------------------------

SELECT
    "Product Name",
    MAX("Product Price") AS highest_price
FROM supply_chain
GROUP BY "Product Name"
ORDER BY highest_price DESC
LIMIT 10;